### ISSUE TITLE
Missing form validation

### ISSUE THREAD

**Issue by saulandreee** [Lizzy0721/MyDashboard#2]
![Screenshot from 2024-11-12 20-15-13](https://github.com/user-attachments/assets/ac2c07a7-8213-4508-b2b5-19d8ba47462a)

Task with white-space title need to be validated

**Comment by Lizzy0721** [comment]
what validation needed for description and deadline field? the same as title? @saulandreee

**Comment by saulandreee** [comment]
just google it. Minimum validation is the field must be filled.
